project_name: telecom-tower-server

builds:
  - binary: telecom-tower-server
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
      - 7
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
      - CC_FOR_TARGET=arm-linux-gnueabihf-gcc
      - CXX_FOR_TARGET=arm-linux-gnueabihf-g++
      - CPATH=/usr/local/include
      - LIBRARY_PATH=/usr/local/lib

archive:
  format: tar.gz
  files:
    - LICENSE
    - README.md

nfpm:
  vendor: Bluemasters
  homepage: https://github.com/telecom-tower/server
  maintainer: Jacques Supcik <jacques@supcik.net>
  description: Telecom Tower gRPC server.
  license: Apache 2.0
  formats:
    - deb
  bindir: /usr/bin
  files:
    "systemd/telecom-tower.service": "/etc/systemd/system/telecom-tower.service"
  config_files:
    "systemd/default": "/etc/default/telecom-tower"