version: 2
jobs:

  setup:
    docker:
      - image: circleci/golang:1.10
    environment:
      - PROTOC_VERSION: "3.5.1"
    steps:
      - run: mkdir -p ${HOME}/workspace
      - run:
          command: wget -q -nc https://github.com/google/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip
          working_directory: /tmp
      - run:
          command: unzip /tmp/protoc-${PROTOC_VERSION}-linux-x86_64.zip
          working_directory: "~/workspace"
      - run: chmod +rx ${HOME}/workspace/bin/protoc
      - run: go get -u google.golang.org/grpc
      - run: go get -u github.com/golang/protobuf/protoc-gen-go
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: cp -a /go/bin/* ${HOME}/workspace/bin
      - persist_to_workspace:
          root: "~"
          paths:
            - workspace

  test:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/telecom-tower/server
    steps:
      - attach_workspace:
          at: "~"
      - run: sudo mkdir -p /usr/local/bin/
      - run: sudo cp -a ${HOME}/workspace/bin/* /usr/local/bin/
      - run: sudo mkdir -p /usr/local/include/google/
      - run: sudo cp -a ${HOME}/workspace/include/google/protobuf /usr/local/include/google/
      - checkout
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install
      - run:
          command: git clone https://github.com/telecom-tower/towerapi.git
          working_directory: /go/src/github.com/telecom-tower/
      - run: go generate
      - run: dep ensure
      - run: gometalinter --deadline 2m main.go
      - run: go test -v ./...
      - run: go build

  deploy:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/telecom-tower/server
    steps:
      - attach_workspace:
          at: "~"
      - run: sudo mkdir -p /usr/local/bin/
      - run: sudo cp -a ${HOME}/workspace/bin/* /usr/local/bin/
      - run: sudo mkdir -p /usr/local/include/google/
      - run: sudo cp -a ${HOME}/workspace/include/google/protobuf /usr/local/include/google/
      - checkout
      - run:
          command: git clone https://github.com/telecom-tower/towerapi.git
          working_directory: /go/src/github.com/telecom-tower/
      - run: go generate
      - run: dep ensure
      - run:
          name: Building and installing C librairie
          command: |
            sudo apt-get install build-essential git scons curl
            echo "deb http://emdebian.org/tools/debian/ jessie main" | sudo tee /etc/apt/sources.list.d/crosstools.list
            curl http://emdebian.org/tools/debian/emdebian-toolchain-archive.key | sudo apt-key add -
            sudo dpkg --add-architecture armhf
            sudo apt-get update
            sudo apt-get install crossbuild-essential-armhf
            mkdir -p ${HOME}/src/lib
            cd ${HOME}/src/lib
            git clone https://github.com/jgarff/rpi_ws281x.git
            cd rpi_ws281x
            scons TOOLCHAIN=arm-linux-gnueabihf
            sudo mkdir -p /usr/local/lib
            sudo cp *.a /usr/local/lib
            sudo mkdir -p /usr/local/include
            sudo cp *.h /usr/local/include
      - run:
          name: Building librarie
          command: |
            sudo chown -R circleci:circleci /usr/local/go/pkg
            go get -v .
          environment:
            GOOS: "linux"
            GOARCH: "arm"
            CGO_ENABLED: "1"
            CC: arm-linux-gnueabihf-gcc
            CC_FOR_TARGET: arm-linux-gnueabihf-gcc
            CXX_FOR_TARGET: arm-linux-gnueabihf-g++
            CPATH: /usr/local/include
            LIBRARY_PATH: /usr/local/lib
      - run: go get -u github.com/goreleaser/goreleaser
      - run: goreleaser
      - run:
          name: Deploy to bintray
          command: |
            FILE=$(ls dist/*linux_armv6.deb | sort -r | head -1)
            BASEFILE=$(basename $FILE)
            VERSION=$(echo $BASEFILE | egrep -o '_[0-9][^_]*?_' | sed -e 's/_//g')
            URL=https://api.bintray.com/content/${BINTRAY_REPO}/${BINTRAY_PKG}/${VERSION}/${BINTRAY_PATH}/${BINTRAY_PKG}/${BASEFILE}\;deb_distribution\=${BINTRAY_DIST}\;deb_component\=${BINTRAY_COMP}\;deb_architecture\=${BINTRAY_ARCH}
            curl -T ${FILE} -u${BINTRAY_USER}:${BINTRAY_KEY} ${URL}
            URL=https://api.bintray.com/calc_metadata/telecom-tower/deb
            # curl -X POST -u${BINTRAY_USER}:${BINTRAY_KEY} https://api.bintray.com/calc_metadata/$BINTRAY_REPO}
          environment:
            BINTRAY_REPO: telecom-tower/deb
            BINTRAY_PKG: telecom-tower-server
            BINTRAY_PATH: pool/main/t
            BINTRAY_DIST: stretch
            BINTRAY_COMP: rpi
            BINTRAY_ARCH: armhf
      - store_artifacts:
          path: dist
          destination: dist
      
workflows:
    version: 2
    default:
      jobs:
        - setup:
            filters:
              tags:
                only: /.*/
        - test:
            requires:
              - setup
            filters:
              tags:
                only: /.*/
        - deploy:
            requires:
              - test
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v[0-9]+(\.[0-9]+).*/
