name: telecom-tower-server
version: '1.2.4'
summary: Telecom Tower Server
description: Server for the Telecom Tower
grade: devel
confinement: devmode
architectures: [ armhf ]
icon: icon.png

apps:
  server:
    daemon: simple
    command: bin/server
    plugs:
      - network
      - network-control

parts:
  server:
    plugin: dump
    source: /snaproot
