name: telecom-tower-server
version: '1.1.0'
summary: Telecom Tower Server
description: Websocket server for the Telecom Tower
grade: devel
confinement: devmode
type: app
architectures: [ armhf ]
icon: icon.png

apps:
  towerserver:
    daemon: simple
    command: bin/towerserver
    plugs:
      - network
      - network-control

parts:
  towerserver:
    plugin: dump
    source: /snaproot
